kind: pipeline
type: docker
name: integration

steps:
- name: build
  image: boulundeasv/dotnet-sdk-with-java
  commands:
  - dotnet build

- name: test
  image: boulundeasv/dotnet-sdk-with-java
  commands:
  - dotnet test
