kind: pipeline
type: docker
name: integration

steps:
- name: code-analysis
  image: boulundeasv/dotnet-sdk-with-java
  environment:
    SONARSECRET:
      from_secret: TokenSecret
  commands:
  - dotnet sonarscanner begin /k:"easv-devops_Docker_Calculator_AY3f7AXeEVvRW2O60EIf" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_52560e24a6ce384bb89d5b13b517d3cc5808d228"  - dotnet build --no-incremental
  - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
  - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

- name: test
  image: boulundeasv/dotnet-sdk-with-java
  commands:
  - dotnet test
