version: '3'

services:
  calculator-app:
    image: dock-calc:1.0
    build:
      context: .
      dockerfile: Dockerfile

  calculator-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    ports:
      - "1433:1433"
